version: '3.9'

services:
  server:
    image: nestjs-orms
    build: .
    container_name: nestjs-orms
    env_file:
      - .env
    networks:
      - database
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - orms_pgdb
    volumes:
      - .:/app
    command:
      yarn run start:dev

  orms_pgdb:
    container_name: orms_pgdb
    image: postgres:14.1
    restart: always
    networks:
      - database
    ports:
      - 5433:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  orms_pgadmin:
    container_name: orms_pgadmin
    image: dpage/pgadmin4
    networks: 
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_MODE: ${PGADMIN_CONFIG_MODE}
    ports:
      - ${PGADMIN_PORT}:80
    restart: unless-stopped
    depends_on:
      - orms_pgdb
    volumes:
      - pgadmin:/var/lib/pgadmin
  
volumes:
  pgdata:
  pgadmin:

networks:
  database:
    driver: bridge