export const schema = {
  type: 'object',
  properties: {
    SERVER_PORT: { type: 'number' },
    SERVER_HOST: { type: 'string' },
    POSTGRES_HOST: { type: 'string' },
    POSTGRES_PORT: { type: 'number' },
    POSTGRES_USER: { type: 'string' },
    POSTGRES_PASSWORD: { type: 'string' },
    POSTGRES_DB: { type: 'string' },
    MIKRO_ENTITIES: { type: 'string' },
    MIKRO_ENTITIES_TS: { type: 'string' },
    MIKRO_PATH: { type: 'string' },
    MIKRO_PATH_TS: { type: 'string' },
    TYPEORM_ENTITIES: { type: 'string' },
  },
  required: [
    'SERVER_PORT',
    'SERVER_HOST',
    'POSTGRES_HOST',
    'POSTGRES_PORT',
    'POSTGRES_USER',
    'POSTGRES_PASSWORD',
    'POSTGRES_DB',
    'MIKRO_ENTITIES',
    'MIKRO_ENTITIES_TS',
    'TYPEORM_ENTITIES',
    'MIKRO_PATH',
    'MIKRO_PATH_TS',
  ],
};
